server:
  port: 18083

spring:
  redis:
    password: 654321
    cluster:
      nodes:
        - 101.43.204.166:1001
        - 101.43.204.166:1002
        - 101.43.204.166:1003
        - 124.222.74.164:1004
        - 124.222.74.164:1005
        - 124.222.74.164:1006
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 10
        # 连接池中的最大空闲连接
        max-idle: 5
        # 连接池中的最小空闲连接
        min-idle: 0
        # 连接池最大阻塞等待时间
        max-wait: 60000


