---
--- Generated by Luanalysis
--- Created by liull.
--- DateTime: 2022/7/4 23:57
---

-- 比较线程标识与锁中是否一致
if(redis.call('get',KEYS[1]) == ARGV[1]) then
    -- 释放锁 del key
    return redis.call('del',KEYS[1])
end
return 0